channels:
  - conda-forge
  - bioconda
dependencies:
  # min version dependencies based on the scanpy recipe
  - python >=3.9  # bioconda: >=3.9, <=3.10
  - python-igraph >=0.10
  - matplotlib-base >=3.6
  - networkx >=2.7
  - numpy >=1.23
  - scanpy >=1.10

  # dev
  - black
  - isort
  - pytest
